nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']  # Ensure this matches your React app's URL
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/': ~
