services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: 5869
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Expose MySQL port

  localhost:
    build:
      context: ./
    ports:
      - "80:8000"  # Expose Symfony app
    networks:
      - app-network
    depends_on:
      - database

  react:
    build:
      context: ./frontend
    ports:
      - "3001:3000"  # Expose React app
    networks:
      - app-network
    depends_on:
      - localhost
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
